### ISSUE TITLE
cant find the dll file 

### ISSUE THREAD

**Issue by andrewmurphy83** [alexwahl/SDRSharp.GpredictConnector#4]
i downloaded the files but no dll file is in the zip to put in the sdrsharp dir

**Comment by weather-tracker** [comment]
it found in the zip file under the release tab on the side.

**Comment by derwahla** [comment]
You can find the zip file on the release page as @weather-tracker pointed out. 
You can also access the release page via this direct link:
https://github.com/alexwahl/SDRSharp.GpredictConnector/releases
